---
stylegan_model: stylegan2-ada-pytorch/ffhq.pkl
seed: 42
dataset: celeba_identities

run_id: gtqw80a5

target_model:
  architecture: densenet121
  num_classes: 20
  weights: ./results/facescrub_densenet121/20250304_000006_HSIC_0_0_OE__celeba_identities_1000/Classifier_0.9674.pth

  bido:
    enable_bido: 0

  outlier_exp:
    enable_OE: 0

config_path: ./wandb/offline-run-20230405_225629-mh0ng5nl/files/configs/training/targets/ResNet18_CelebA_test.yaml

evaluation_model:
  architecture: inceptionv3
  num_classes: 1000
  weights: ./results/inceptionv3_celeba3/Classifier_0.9334.pth

candidates:
  num_candidates: 200
  candidate_search:
    search_space_size: 5000
    center_crop: 800
    resize: 224
    horizontal_flip: true
    batch_size: 25
    truncation_psi: 0.5
    truncation_cutoff: 8

attack:
  batch_size: 10
  num_epochs: 70
  targets: [0, 1, 2, 3, 4]
  discriminator_loss_weight: 0.0
  single_w: true
  clip: false
  transformations:
    CenterCrop:
      size: 800
    Resize:
      size: 224
    RandomResizedCrop:
      size: [224, 224]
      scale: [0.9, 1.0]
      ratio: [1.0, 1.0]

  optimizer:
    Adam:
      lr: 0.005
      weight_decay: 0
      betas: [0.1, 0.1]

final_selection:
  samples_per_target: 50
  approach: transforms
  iterations: 100

wandb:
  enable_logging: false
  wandb_init_args:
    project: model_inversion_attacks
    save_code: true
    name: Attack_CelebA_FFHQ
