---
seed: 42

model:
  architecture: densenet121
  num_classes: 1000
  pretrained: true

dataset:
  type: celeba_identities
  validation_set_size: 0
  image_size: 224

transformations:
  RandomResizedCrop:
    size: [224, 224]
    scale: [0.85, 1]
    ratio: [1, 1]
  RandomHorizontalFlip:
    p: 0.5

optimizer:
  Adam:
    lr: 0.0005
    betas: [0.9, 0.999]
    weight_decay: 0

lr_scheduler:
  MultiStepLR:
    milestones: [50]
    gamma: 0.2

training:
  num_epochs: 80
  batch_size: 64
  dataloader_num_workers: 8
  save_path: results/

rtpt:
  experiment_name: Training target classifier
  name_initials: XX

wandb:
  enable_logging: false
  args:
    project: CelebA_train
    name: Densenet121_CelebA
    save_code: true

bido:
  enable_bido: true
  params:
    measure: HSIC
    alpha: 0.01
    beta: 0.1

outlier_exp:
  enable_OE: false
  mode: random_OE
  reweighting: false
  aux_ood_dataset: celeba_identities
  params:
    ood_factor: 1